version: "3.9"

services:
  threatmark-ai-bot:
    container_name: vulnerability-scanner-bot

    build:
      context: .
      dockerfile: Dockerfile
      args:
        INCLUDE_DEV: "false"

    environment:
      # Core runtime
      PYTHONUNBUFFERED: "1"
      LOGURU_LEVEL: "INFO"
      TZ: "Europe/Prague"

      # Slack
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_CHANNEL_NAME: ${SLACK_CHANNEL_NAME}
      POLL_INTERVAL: ${POLL_INTERVAL:-60}

      # Alerts
      ALERT_EMAILS: ${ALERT_EMAILS}
      ALERT_THRESHOLD: ${ALERT_THRESHOLD:-4}

      # LLM connector
      LITELLM_MODEL: ${LITELLM_MODEL}
      LITELLM_BASE_URL: ${LITELLM_BASE_URL}
      LITELLM_API_KEY: ${LITELLM_API_KEY}

    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts

    restart: unless-stopped

    # ✅ Runs your Channel Monitor version of main_threatintel
    command: ["uv", "run", "-m", "src.main_threatintel"]

    healthcheck:
      test: ["CMD", "test", "-n", "$$SLACK_BOT_TOKEN"]
      interval: 60s
      timeout: 5s
      retries: 3
