services:
  tm_threat_sentinel:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - tm_threat_sentinel_data:/app/data
      - ./scripts:/app/scripts
    command: ["uv", "run", "-m", "src.main_threatintel"]
    restart: unless-stopped


volumes:
  tm_threat_sentinel_data:
    name: tm_threat_sentinel_data
