version: "3.9"

services:
  tm_threat_sentinel:
    container_name: tm_threat_sentinel-bot

    build:
      context: .
      dockerfile: Dockerfile
      args:
        INCLUDE_DEV: "false"   # Skip dev dependencies in production

    environment:
      # Core runtime
      PYTHONUNBUFFERED: "1"
      LOGURU_LEVEL: "INFO"
      TZ: "Europe/Prague"

      # Slack integration
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_CHANNEL_NAME: ${SLACK_CHANNEL_NAME}
      POLL_INTERVAL: ${POLL_INTERVAL:-60}

      # Alerts
      ALERT_EMAILS: ${ALERT_EMAILS}
      ALERT_THRESHOLD: ${ALERT_THRESHOLD:-4}

      # LLM connector (LiteLLM Proxy / Bedrock)
      LITELLM_MODEL: ${LITELLM_MODEL}
      LITELLM_BASE_URL: ${LITELLM_BASE_URL}
      LITELLM_API_KEY: ${LITELLM_API_KEY}

    # Persistent data storage
    volumes:
      - tm_threat_sentinel_data:/app/data
      - ./scripts:/app/scripts

    # Always restart unless explicitly stopped
    restart: unless-stopped

    # Run main entrypoint
    command: ["uv", "run", "-m", "src.main_threatintel"]

    # Healthcheck (validates Slack token presence)
    healthcheck:
      test: ["CMD", "test", "-n", "$$SLACK_BOT_TOKEN"]
      interval: 60s
      timeout: 5s
      retries: 3

    # Ensure Playwright dependencies available (if needed)
    shm_size: "2gb"

volumes:
  tm_threat_sentinel_data:
    name: tm_threat_sentinel_data
